// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzVDVtbXcdS3QTUwSLWq6Bi12NDnuog7I',
    appId: '1:1054498550686:android:45161e8d4110a650a71c8f',
    messagingSenderId: '1054498550686',
    projectId: 'flutter1-8b0ca',
    storageBucket: 'flutter1-8b0ca.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9srgXMjzq_0UX3PYPBWW2Gxshkcb3e2Y',
    appId: '1:1054498550686:web:674ff66dbc03c5ffa71c8f',
    messagingSenderId: '1054498550686',
    projectId: 'flutter1-8b0ca',
    authDomain: 'flutter1-8b0ca.firebaseapp.com',
    storageBucket: 'flutter1-8b0ca.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyD2eqbAtJToNoxgG7k_dGyW1CU3jhRpk',
    appId: '1:1054498550686:ios:6b3cbe0c5bfdacdba71c8f',
    messagingSenderId: '1054498550686',
    projectId: 'flutter1-8b0ca',
    storageBucket: 'flutter1-8b0ca.firebasestorage.app',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyD2eqbAtJToNoxgG7k_dGyW1CU3jhRpk',
    appId: '1:1054498550686:ios:6b3cbe0c5bfdacdba71c8f',
    messagingSenderId: '1054498550686',
    projectId: 'flutter1-8b0ca',
    storageBucket: 'flutter1-8b0ca.firebasestorage.app',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9srgXMjzq_0UX3PYPBWW2Gxshkcb3e2Y',
    appId: '1:1054498550686:web:2a20c447937ac6c1a71c8f',
    messagingSenderId: '1054498550686',
    projectId: 'flutter1-8b0ca',
    authDomain: 'flutter1-8b0ca.firebaseapp.com',
    storageBucket: 'flutter1-8b0ca.firebasestorage.app',
  );

}